FROM rust:1.84.1 as builder

WORKDIR /app
COPY . .

RUN cargo build

FROM debian:bookworm-slim

WORKDIR /app
RUN useradd -m appuser

COPY --from=builder /app/target/debug/wik_dps_tp01 /app/wik_dps_tp01

USER appuser
EXPOSE 8080
CMD ["/app/wik_dps_tp01"]
